### ISSUE TITLE
ARR code, relicensed under GPL-3.0

### ISSUE THREAD

**Issue by Lisenaaaa** [SkyblockClient/Skyclient-bot#18]
This is all code from Rain-TEMP, located at https://github.com/Lisenaaaa/Rain-TEMP. Sure, some of it has been updated, changed, and improved, but it's still originally from Rain-TEMP. Which, if you didn't know, is licensed under ARR.

*slight edit: I believe code with no license specified is ARR. Because it's on GitHub, there's some bending of those rules, but I've always considered (publicly) that Rain, and it's derivatives, are ARR. The way I've handled that is by saying something along the lines of "if you want to use my code, ask me"*

I've been in contact with Wyvest, who says that y'all are planning on switching away from Rain's code.
![image](https://user-images.githubusercontent.com/69115669/194776024-d4d74806-c1eb-4e7d-a40f-603465d19b38.png)
You have two weeks to completely deprecate this repository, and rewrite it from the ground up, or I'll, well, do what I can, as a teenager, to get this repository taken down. If y'all want, I can make a Hypixel forum post about it, too.

Alternatively, you can produce proof of me saying that you can take my ARR code, and relicense it under GPL-3.0. I have no memory of saying that, so good luck.

I'm trying to think of a good metaphor for this, but I can't.

**Comment by nacrt** [comment]
![grafik](https://user-images.githubusercontent.com/37629791/194776682-7a84f269-72f3-445a-9a78-1b5a77acc96f.png)
it's awfully convenient for you to suddenly care about the bots license now that you have been banned from the project

**Comment by Lisenaaaa** [comment]
I was banned from the project because I banned someone who was misgendering people. Somehow, that caused me to be banned.

**Comment by nacrt** [comment]
You were banned because you joked about doxxing me

**Comment by Lisenaaaa** [comment]
oh right that fuck

**Comment by Lisenaaaa** [comment]
from what i remember, i banned brian for misgendering, then i left the server. people then went to somewhere i considered to be safe, and gave me a hard time about it. *i don't know the exact order of events*, but i was really angry. i'm not defending my actions. i don't know when i got banned, or when i sent that message.

i did deserve to get banned for that. but yes, i do now care about the license. get my code off your platform.

**Comment by nacrt** [comment]
that's really unfortunate

**Comment by Lisenaaaa** [comment]
get my code out of skyclient

**Comment by Madeleaan** [comment]
https://github.com/paradite/github-dramas

**Comment by UnderscoreRayless** [comment]
We will try to remove it within the next 2 weeks

**Comment by Lisenaaaa** [comment]
Good.
